export const Routes = {
  HOME: '/',
  MENU: '/main-menu',
  LOGIN: '/sign-in',
  REGISTER: '/register',
  SETTINGS: '/settings',
  DICTIONARY: '/dictionary',
  TIMER: '/timer',
  ADMIN_SWIMMERS: '/admin/swimmers',
  ADMIN_COACHES: '/admin/coaches',
  ADMIN_USER_PROFILE: '/admin/user/:userEmail',
  COACH_MY_SWIMMERS: '/coach/my-swimmers',
  COACH_ALL_SWIMMERS: '/coach/all-swimmers',
  COACH_ADD_WORKOUT: '/coach/add-workout/:userEmail',
  COACH_SWIMMER_PROFILE: '/coach/user/:userEmail',
};
